### ISSUE TITLE
Upload injects extra subdirectory when destination folder exists on s3 already

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-alchemist#5]
happens when process is killed half way through upload.

https://github.com/opendatacube/datacube-alchemist/blob/4ffd9da91753bda73b9665c5e665fb0b2f5771a2/datacube_alchemist/upload.py#L28-L30

**Comment by Kirill888** [comment]
The docs for `fs.put(...)` don't say much, but code does this:

```python

**Comment by dunkgray** [comment]
I different upload message is used now.
