### ISSUE TITLE
No matching distribution found for wofs==1.6.1

### ISSUE THREAD

**Issue by james-blitzm** [opendatacube/datacube-alchemist#83]
From fresh clone, then docker compose up:

`#10 8.828 ERROR: No matching distribution found for wofs==1.6.1 (from -r /tmp/requirements.txt (line 7))`

**Comment by james-blitzm** [comment]
I can see  v1.6.1 package is not yet published here: https://packages.dea.ga.gov.au/wofs/

**Comment by alexgleith** [comment]
Ah, I didn't read the manual... https://github.com/GeoscienceAustralia/wofs#releases

**Comment by alexgleith** [comment]
Try now :-)

**Comment by alexgleith** [comment]
Looks fine https://github.com/opendatacube/datacube-alchemist/runs/2330021673?check_suite_focus=true

Closing
